require('core.plugin_config.theme')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.gitsigns')
require('core.plugin_config.treesitter')
require('core.plugin_config.mason')
require('core.plugin_config.completions')
require('core/plugin_config.lsp_config')
require('core.plugin_config.which-key-register')
